name: test

on:
  push:

jobs:

  multi:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run: docker build .

  linux:
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run: docker build -f Dockerfile.linux .

  windows:
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run: docker build -f Dockerfile.windows .